# Generated by Django 4.2.1 on 2023-05-20 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReservationsTennis', '0002_alter_userprofile_selected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Tennis_userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
